### ISSUE TITLE
Weak copyleft licence

### ISSUE THREAD

**Issue by stucox** [avian2/unidecode#1]
Is there any chance this could be released with a weak copyleft licence (e.g. BSD or MIT)?

**Comment by avian2** [comment]
BSD and MIT are not [copyleft](https://en.wikipedia.org/wiki/Copyleft) licenses. 

No, I have no plans to release Unidecode under a different license. See https://github.com/kmike/text-unidecode for a similar library under an Artistic License.

**Comment by makeworld-the-better-one** [comment]
@avian2 Why not use LGPL, which will allow for wider usage of the library, but still applies copyleft constraints to your library's code?


There's also [anyascii](https://github.com/anyascii/anyascii), which is under the ISC license and [claims](https://github.com/anyascii/anyascii#unidecode) to give better results than Unidecode and all its ports, like this library.
