### ISSUE TITLE
Move to semantic versioning

### ISSUE THREAD

**Issue by avian2** [avian2/unidecode#13]
Traditionally Python Unidecode followed the versioning scheme used by the original Perl module. This doesn't make sense any more because:

* Perl Text::Unidecode itself switched to a different versioning scheme long ago - http://search.cpan.org/~sburke/Text-Unidecode-1.30/
* Python Unidecode has now sufficiently diverged from Perl version so that matched version numbers are no longer useful,
* setuptools (>= 8) began mangling version numbers, yielding confusion because Unidecode 0.04.x now sometimes appears as 0.4.x - https://github.com/pypa/setuptools/issues/302

Next release should be numbered something like `1.0.22`.

**Comment by FRidh** [comment]
Would you mind making a re-release of 0.04.21 as 0.4.21? Then we can use semantic versioning right away. 

The reason I am asking is that this is the only package I encountered which breaks usage of `packaging.version.Version` (https://github.com/pypa/packaging/blob/16.8/packaging/version.py#L191) as also encountered by `setuptools`. I'm working on an update script for our distribution (NixOS) and prefer not having to modify `Version` to by-pass this.

**Comment by avian2** [comment]
I'll just release 1.0.22 as planned in a day or two. git master contains some contributions that I think are ready for release.

**Comment by avian2** [comment]
I've just released Unidecode 1.0.22, hence I'm closing this issue.
