### ISSUE TITLE
Language parameter?

### ISSUE THREAD

**Issue by bittlingmayer** [avian2/unidecode#15]
Major scripts like Latin, Cyrillic and Arabic are used to write many languages.  Right now, the lib is implicitly unidecoding all Cyrillic as if it were Russian specifically.

For example:  
`unidecode('Халид Бешлић, Цеца,  Жељко Јоксимовић') # sr`

actual:
`'Khalid Beshlitsh, Tsetsa,  Zheljko Joksimovitsh'`

expected:  
`'Halid Beslic, Ceca, Zeljko Joksimovic'`

That's because there should be an implicit initial conversion to Latin (`'Halid Bešlić, Ceca, Željko Joksimović'`).  Passing that to `unidecode` works as expected.

Similar is true for Latin.  For example:
`unidecode('Kadıköy') # tr`  
`unidecode('Schönheimer') # de`

actual:
`'Kadikoy'`  
`'Schonheimer'`

expected:
`'Kadikoy'`  
`'Schoenheimer'`

The most straightforward fix is an optional parameter `lang`.

**Comment by avian2** [comment]
Sorry, language-dependent transliteration is out of scope of Unidecode. There are other projects that do that. You might want to use [Unihandecode](https://github.com/miurahr/unihandecode) instead for example, which does implement a `lang` parameter.

I understand that this is a very common problem, but it will not be fixed in this library. Please see arguments in the following on why Unidecode will not go beyond context-free character replacements:

https://www.tablix.org/~avian/blog/archives/2013/09/python_unidecode_release_0_04_14/

http://search.cpan.org/~sburke/Text-Unidecode-0.04/lib/Text/Unidecode.pm

**Comment by bittlingmayer** [comment]
Fair enough, I understand this is a very hard task to do well and impossible to do perfectly (and thank you for the links to enjoyable reading and to unihandecode).

I see the current behaviour for Cyrillic -- favouring the Russian interpretation over others -- as unfortunately similar to the undesirable behaviour with ö and ü -- favouring the German interpretation.

So in that sense, it's inconsistent with your stated principle.  On the other hand, to change it now would be inconsistent with the principle of not breaking existing code.

**Comment by avian2** [comment]
As a Slovenian native speaker I find the Serbian transliteration more understandable as well. Alas, I'm an engineer not a linguist. Hence I trust Sean Burke, who originally wrote Unidecode and is way more qualified to decide on such things. After the whole German umlaut issue I'm very hesitant to accept changes like that.

You might want to raise the issue with him. If he changes Cyrillic tables in his Perl module I would be happy to accept the same change in Python Unidecode.

**Comment by user2589** [comment]
@bittlingmayer,

I couldn’t find a better way to contact you so I’m writing here. This comment will be deleted in one week to keep the issue discussion clean.

My name is Marat, I am a PhD student at Carnegie Mellon University. As a part of my research, I’m trying to better understand the sources of issue reports in open source.

Can you please help me by answering few questions about this issue? It shouldn’t take more than a couple of minutes. Here’s the google form: [link](https://docs.google.com/forms/d/e/1FAIpQLSfTlhMeh25AZAr0wy-DNBki_HzFP_fqdT3eIk1mf7b80mg8Lg/viewform?usp=pp_url&entry.2074867396=https://github.com/avian2/unidecode/issues/15)

I will share everything I learn from answers to this survey with the community afterwards.

Thank you very much!
