### ISSUE TITLE
Performance improvement for frequent ASCII transliterations

### ISSUE THREAD

**Issue by dukebody** [avian2/unidecode#2]
I have a case where most transliterations only have to deal with ASCII chars, with only a few taking non-ASCII ones (Spanish).

See https://github.com/iki/unidecode/pull/11#issuecomment-148920908

PR will follow.

**Comment by avian2** [comment]
Fixed in https://github.com/avian2/unidecode/commit/0c47a034eb9f88b7747c79a82b0d03809bb5e1f6
