### ISSUE TITLE
Consider dual licensing under Perl Artistic

### ISSUE THREAD

**Issue by bolkedebruin** [avian2/unidecode#23]
Hi,

I am one of the maintainers of Apache Airflow. Indirectly we make use of unidecode through a dependency (python-nvd3 -> python-slugify -> unidecode). The Apache Software Foundation considers the GPLv2 incompatible with the APL2. 

We didn't find out about the issue until now due to the fact that nvd3 and python-slugify maintain compatible licensed. Python-slugify is MIT licensed which might be incompatible with GPLv2 (I am not a lawyer).

We could ask python-slugify to use an alternative library or implement our own. Both are obviously a hassle as we need to convince package maintainers to switch. Also there is not technical reason to do so for us.

As the original Perl package was also available under the Perl Artistic License, would you consider dual licensing your derivative? That would allows us to continue to use the very useful libraries and just make us very happy :-).

Thanks for your consideration in advance!
Bolke

**Comment by bolkedebruin** [comment]
@avian2 quick question, which might resolve all: do you consider python-slugify using unidecode as a python module a derivative work from unidecode?

**Comment by avian2** [comment]
No, I don't consider python-slugify as a derivative work from unidecode. I agree with what @un33k said in https://github.com/un33k/python-slugify/issues/7.

[FSF's interpretation](https://www.gnu.org/licenses/gpl-faq.html#IfInterpreterIsGPL) of GPL is that using interpreted libraries (like Python modules) triggers the derivative clause. However Unidecode basically provides a single function, and obviously libraries other than unidecode already exist that can provide other implementations of that function. It's hard to argue that simply using this interface makes any code "based on unidecode".

**Comment by bolkedebruin** [comment]
Thanks. That probably solves the issue.
