### ISSUE TITLE
Support localization

### ISSUE THREAD

**Issue by PanderMusubi** [avian2/unidecode#27]
Please, support localization for Unicode block and character description translations from https://github.com/unicode-table/unicode-table-data/tree/master/loc If possible, use a `gettetxt` approach similar to https://pypi.org/project/pycountry/ Implementing this feature will allow users to read Unicode descriptions in their own language, other than English.

**Comment by avian2** [comment]
I don't understand. Unidecode does not "allow users to read Unicode descriptions" and does not contain "Unicode block and character descriptions".

**Comment by PanderMusubi** [comment]
Use localization from the files of unicode-table to translate descriptions of Unicode characters. For example, now is possible only in English:

    from unicodedata import name
    print(name('ß'))
    LATIN SMALL LETTER SHARP S

So unidecode could provide a way to translate `LATIN SMALL LETTER SHARP S` to e.g. German with (proposed code):

    from unicodedata import name
    from gettext import translation
    from unidecode import LOCALED_DIR
    german = translation('Unicode' LOCALED_DIR, languages=['de'])
    german.install()
    print(_(name('ß')))
    LATEINISCHER KLEINBUCHSTABE SCHARFES S

**Comment by PanderMusubi** [comment]
Indeed, my bad. Sorry and gonna move the issue to there. Thanks.
