### ISSUE TITLE
Support for Latin Extended-D ?

### ISSUE THREAD

**Issue by PonteIneptique** [avian2/unidecode#49]
Hi there,
I find myself in a particuliar situation where I deal with manuscripts transcriptions. Of course, some char are not valid in unicode, but some seems to be from my understanding : 

```python
	unidecode.x0f1
	unidecode.x0e6
	unidecode.x0f0
ꝛ	unidecode.x0a7
	unidecode.x0f0
	unidecode.x0f0
	unidecode.x0e8
	unidecode.x0f0
	unidecode.x0e5
	unidecode.x0e4
ꝓ	unidecode.x0a7
	unidecode.x0f1
	unidecode.x0f0
	unidecode.x0f7
	unidecode.x0e6
	unidecode.x0e7
	unidecode.x0e5
	unidecode.x0ee
ꝰ	unidecode.x0a7
ꝙ	unidecode.x0a7
ꝯ	unidecode.x0a7
	unidecode.x0f1
	unidecode.x0f1
	unidecode.x0f1
	unidecode.x0f1
ꝑ	unidecode.x0a7
	unidecode.x0e8
	unidecode.x0f1
```

Should I pull request for x0a7 and x0f7 ?

**Comment by avian2** [comment]
Sorry, I don't understand what you are trying to say here.

**Comment by PonteIneptique** [comment]
Sorry. Apparently, x0a7 and x0f7 spaces are not present in Unidecode, so my question is : is unidecode ok for supporting it ?

**Comment by avian2** [comment]
If you have any transliterations to contribute for characters in the U+A7xx block, please send a pull request.

U+F7xx block is in a private use area. I don't think Unidecode can make any assumptions on what those characters represent, so it can't include transliteration for those.
