### ISSUE TITLE
issues on Transliteration of Japanese Kanji and Chinese Kanji

### ISSUE THREAD

**Issue by zjFFFFFF** [avian2/unidecode#55]
Thank you for your work.

`>>> unidecode("人生は難しいですね。")
'Ren Sheng haNan shiidesune. '`

This is a Japanese sentence with Kanji.
Although the kana(like は and しいですね。) is correctly transliterated, Kanji is not correctly transliterated.

In Chinese, 人生 = Ren Sheng , 難 = Nan.
But it should be 人生=jinsei, 難 = muzuka　here, since it is a sentence in japanese. Can this problem be solved?

**Comment by avian2** [comment]
Yes. Please use [Unihandecode](https://github.com/miurahr/unihandecode) instead.
