### ISSUE TITLE
Tironian "et" being changed to numeral, 7

### ISSUE THREAD

**Issue by AdeDoyle** [avian2/unidecode#57]
Hi.

I've noticed that the Unicode character, "⁊", a Tironian note standing for Latin "et", is being changed to the numeral, "7". While they look alike, this doesn't seem like the best way to decode it, as it is never used to represent a numeral.

In Old Irish and Latin texts it was used as short-hand for the full word "et", so perhaps it should be replaced with "et". Alternatively, it is still used as an ampersand in modern Irish, so, maybe "&" would be a better replacement option?

Le meas,
Adrian.

**Comment by avian2** [comment]
Hi. thanks for your comment. I'm not familiar with Irish language. Based on what you said I'm more in favor of changing it to "&".

**Comment by AdeDoyle** [comment]
I think that would make the most sense in a modern context. I don't believe it continues to be used in languages other than Irish, except in variant abbreviations of the Latin expression, "et cetera", such as "⁊rl." and "ꝛc."

**Comment by avian2** [comment]
Fixed. Thanks.
