### ISSUE TITLE
Add a Homepage to the pypi listing

### ISSUE THREAD

**Issue by feelepxyz** [avian2/unidecode#58]
👋  Could you add this repo as the "homepage" for the pypi listing for unidecode? https://pypi.org/project/Unidecode/

Spotted an issue in a Dependabot pull request upgrading unidecode where the dependency url goes to the wrong repo: https://github.com/kmike/text-unidecode

Example pull request: https://github.com/metabrainz/listenbrainz-server/pull/1219

For reference, Dependabot tries to find the "homepage" for the dependency from the pypi json response, first looking at any homepage entries and if none exist scanning the description for any source repo links. In this case the description for Unidecode on pypi includes a link to text-unidecode before the correct github link under the license section `Unidecode should use a permissive license such as MIT or the BSD license.`.

**Comment by avian2** [comment]
Hi. This seems to me more like an issue with Dependabot. Taking the first GitHub link appearing in the description as the canonical link for the project certainly seems like a bad idea in general. I'm sure I'm not the only person out there linking to related projects.

I'm baffled why Dependabot tries so hard to guess a link to GitHub in the first place - certainly not every Python package has one. I think it would be better to just link to the PyPI page in an absence of a homepage field. PyPI package page is the closest thing Unidecode has to a "homepage". I don't see the need to maintain a separate page for it.

I'm hesitant to give this GitHub repository any more weight than it currently has. It is only an up-to-date mirror of my own git repository.

**Comment by feelepxyz** [comment]
@avian2 fair point! Will have a think about changing this in dependabot.
