### ISSUE TITLE
1.3.0 wheel incorrectly claiming Python 2 support.

### ISSUE THREAD

**Issue by YKdvd** [avian2/unidecode#69]
Version 1.3.0 dropped support for Python <3.5, include Python 2.  But the setup.cfg didn't change the "universal=1" line, so wheels are still being created with names like this: "Unidecode-1.3.0-py2.py3-none-any.whl", which claim Python 2 support when this is not true.
https://github.com/avian2/unidecode/blob/9c2dc90abda2726227847f0c4ab0c50e13240cd1/setup.cfg#L2

That line should probably also removed, a new 1.3.1 built, and a PyPI"yank" request done on the current 1.3.0, since as long as it is there pip will incorrectly consider it the most recent Python 2 compatible version, instead of the proper 1.2.0?

**Comment by avian2** [comment]
Thank you for reporting! Should be fixed now.
