### ISSUE TITLE
Input() Method

### ISSUE THREAD

**Issue by harsh7i** [avian2/unidecode#80]
### Hello Sir
As you said in your documentation
I used the code, and the code is working
It successfully decode unicode escape characters.
```shell
>> from unidecode import unidecode
>> value="\u0048\u0065\u006c\u006c\u006f"
>> print(unidecode(value))
Hello
```

### Problem
When i used input as a value
`unidecode` prints the same value as i entered.
```shell
>> from unidecode import unidecode
>> value=input("Input: ")
Input: \u0048\u0065\u006c\u006c\u006f
>> print(unidecode(value))
\u0048\u0065\u006c\u006c\u006f
```

**Comment by avian2** [comment]
Unidecode does not decode escape sequences. You are using a wrong library. See the "Why does Unidecode not replace \u and \U backslash escapes in my strings?" frequently asked question in the README.

**Comment by harsh7i** [comment]
> Unidecode does not decode escape sequences. You are using a wrong library. See the "Why does Unidecode not replace \u and \U backslash escapes in my strings?" frequently asked question in the README.

### Hello @avian2 
I can understand what you told.
But sir our tool was successfully worked with a defined string of escape sequences. The only problem appears with input() method.
If you can, help me !
