### ISSUE TITLE
license of data files

### ISSUE THREAD

**Issue by codinguncut** [avian2/unidecode#9]
Hi Tomaž,

can you clarify the license of the data/mapping files?
The original Text-Unidecode was released as Clarified Perl Artistic License.
I am currently working on a transliteration library under MIT license and would love to make use of your excellent updates/refinements to the mapping files.

Would you be willing to release your updated mappings under a dual Clarified Perl Artistic / GPL license? I have also contacted the original Perl author, whether he's willing to release his code under Perl Artistic License 2.0...

Sorry for all the back and forth.

Regards,
Johannes

**Comment by avian2** [comment]
Hi Johannes

Python port of Unidecode is licensed under GPL 2 or later, as it says in the README file.

Python port is derived from Perl Unidecode 0.04 package which was dual licensed GPL or Artistic license. I chose GPL based on feedback that Perl-style dual-licensing is unusual and confusing for Python packages and because I personally find GPL more fitting.

There are different opinions on whether these licenses can apply to data files.

I have already been involved in one too many long discussion regarding Unidecode licensing. I'm very hesitant to have another one. At this point I'm not changing the license without a very good reason.

**Comment by lrq3000** [comment]
Can you add this info into the readme please?

**Comment by codinguncut** [comment]
to be honest, while being a big "license guy", I'm a bit unsure about the data files.
if I created a document containing all unicode characters, ran unidecode over it and saved the output, what license would the output file be under? I assume it would be unlicensed, since the GPL does not apply to program outputs in general...

**Comment by avian2** [comment]
Generally speaking, databases that contain creative work tend to have copyright protection. Unicode Inc. certainly thinks their character database deserves a copyright notice and a license agreement.

http://www.unicode.org/copyright.html

I can also say that non-trivial amount of manual work went into the Unidecode data files, both by Sean, me and other contributors.

In my opinion there's a difference between output produced by Unidecode during normal use and systematically copying it's database. I think an analogy would be using an English dictionary to look up some words you are going to use in a new book versus publishing a verbatim copy of the dictionary.

**Comment by scharf** [comment]
...this means the library [cannot be used in commercial software](https://softwareengineering.stackexchange.com/questions/47032/can-i-use-gpl-software-in-a-commercial-application) that does not want to make its entire code open source... 

The [Artistic License](https://en.wikipedia.org/wiki/Artistic_License), on the other hand, allows you to use the library in commercial products without having to make your entire product open source. However, it restricts shipping modified versions of the library itself.

See also https://snyk.io/blog/over-10-of-python-packages-on-pypi-are-distributed-without-any-license/

**Comment by avian2** [comment]
@scharf Unidecode is not distributed without a license. It is distributed under the GNU General Public License, version 2 or later, as specified in the README and PyPi package metadata.

I will not discuss the GPL vs. Artistic license again. See FAQ in the README.
