### ISSUE TITLE
PyPI Wheels include `__init__.pyi`

### ISSUE THREAD

**Issue by reytchison** [avian2/unidecode#90]
The PyPI wheels contain `__init__.pyi` (checked 1.3.6). Is this intended? This commit removed `__init__.pyi` two years ago: https://github.com/avian2/unidecode/commit/f8775394b421eaf47cb7c13eb1cc187550b3183c. It looks like the file is for type annotations, but type annotations have since been added in `__init__.py`. Thank you!

**Comment by avian2** [comment]
Unidecode 1.3.7 is on PyPi now.
